- Type :: White Sparkling, Brut
- Producer :: [[barberry:/producers/10c5a427-ee4a-4962-a855-a9bbfd135d39][Cà del Vént]]
- Vintage :: 2014
- Location :: Italy, Vino (IT)
- Grapes :: Chardonnay, Pinot Noir
- Alcohol :: 12.5
- Sugar :: NA
- Price :: 1412 UAH, 1518 UAH, 1650 UAH
- Cellar :: N/A

** Ratings

*** 2020-12-18 - ☆ 8.00

Very cool traditional style sparkling that decided to drop Franciacorta DOCG from the label. Powerful and rich nose, with oxidative notes, apple tart, honey. Well balanced, but lacks freshness (just a tiny bit). I am very happy to witness great effort.

*** 2021-08-17 - ☆ 8.25

Tasted as part of Divych Vechir.

Beautiful wine. Tasting again in almost a year and it become even better. Sea breeze, cream, dough, mildew (in a very good way), marzipan, baked apples, ginger. Sophisticated, expressive, delicious but friendly and approachable. I agree with people who say that it lacks acidity to achieve perfection. Definitely great alternative to Champagne, good QPR. Hope to taste other wines from this range.

*** 2021-12-21 - ☆ 8.50

Tasted as part of Classy Bubbles event.

Constantly delivers. Wonderful table wine (!). Charming bouquet full of nuts, baked apples, soaked apples, honey, ginger, citrus and toast. Complex, and demanding. Well balanced, right volume, tasty with long and flavourful aftertaste. Definitely one of my favourite traditional sparkling wines. And great value, btw.

** Related

#+begin_export html
<div class="flex-container">
  <a class="flex-item flex-item-left" href="/wines/bf77c1a9-c3da-424d-8306-f94769b95a65.html">
    <section class="h text-small text-lighter">Cà del Vént</section>
    <section class="h text-bolder">Sospiri Brut Riserva Pas Operé - 2011</section>
  </a>

</div>
#+end_export
