:PROPERTIES:
:ID:                     c723619f-2d47-49b5-ab28-a2f34ffabf87
:END:
- Type :: White Sparkling, Brut
- Producer :: [[barberry:/producers/10c5a427-ee4a-4962-a855-a9bbfd135d39][Cà del Vént]]
- Vintage :: 2014
- Location :: Italy, Vino (IT)
- Grapes :: Chardonnay, Pinot Noir
- Alcohol :: 12.5
- Sugar :: NA
- Price :: 1412 UAH, 1518 UAH, 1650 UAH
- Cellar :: N/A

** Ratings
:PROPERTIES:
:ID:                     a5761613-c529-4f2b-9419-3ae11c1b6174
:END:

*** 2020-12-18 - ☆ 8.00
:PROPERTIES:
:ID:                     44b05be2-3909-4aab-95b3-ab74de2994c6
:END:

Very cool traditional style sparkling that decided to drop Franciacorta DOCG from the label. Powerful and rich nose, with oxidative notes, apple tart, honey. Well balanced, but lacks freshness (just a tiny bit). I am very happy to witness great effort.

*** 2021-08-17 - ☆ 8.25
:PROPERTIES:
:ID:                     9b17abbf-a40e-41f1-8dc9-38967465a703
:END:

Tasted as part of Divych Vechir.

Beautiful wine. Tasting again in almost a year and it become even better. Sea breeze, cream, dough, mildew (in a very good way), marzipan, baked apples, ginger. Sophisticated, expressive, delicious but friendly and approachable. I agree with people who say that it lacks acidity to achieve perfection. Definitely great alternative to Champagne, good QPR. Hope to taste other wines from this range.

*** 2021-12-21 - ☆ 8.50
:PROPERTIES:
:ID:                     f95371af-c938-423f-9d28-6ea28ab932e7
:END:

Tasted as part of [[barberry:/posts/2021-12-21-classy-bubbles][Classy Bubbles]] event.

Constantly delivers. Wonderful table wine (!). Charming bouquet full of nuts, baked apples, soaked apples, honey, ginger, citrus and toast. Complex, and demanding. Well balanced, right volume, tasty with long and flavourful aftertaste. Definitely one of my favourite traditional sparkling wines. And great value, btw.

** Related
:PROPERTIES:
:ID:                     042a17ad-7c65-4e12-b877-aa90342bf3e5
:END:

#+begin_export html
<div class="flex-container">
  <a class="flex-item flex-item-left" href="/wines/bf77c1a9-c3da-424d-8306-f94769b95a65.html">
    <section class="h text-small text-lighter">Cà del Vént</section>
    <section class="h text-bolder">Sospiri Brut Riserva Pas Operé - 2011</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/f02e451d-3dc2-4b53-a59b-98a8d7144471.html">
    <section class="h text-small text-lighter">Cà del Vént</section>
    <section class="h text-bolder">Sogno Blanc de Blancs Pas Operé - 2014</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/03c58432-e29b-470c-985b-a1fa44ac3df7.html">
    <section class="h text-small text-lighter">Bérêche & Fils</section>
    <section class="h text-bolder">Brut Réserve - NV</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/108c69b0-4506-4e05-9da4-c73ccd053992.html">
    <section class="h text-small text-lighter">Shabo</section>
    <section class="h text-bolder">Grand Reserve Extra Brut - NV</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/12c59914-f654-4202-bf19-1eb27dcbd4f0.html">
    <section class="h text-small text-lighter">Billecart Salmon</section>
    <section class="h text-bolder">Brut Reserve - NV</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/3811fe0e-abd2-43f1-b405-4133d488b8e7.html">
    <section class="h text-small text-lighter">Marco de Bartoli</section>
    <section class="h text-bolder">Terzavia - 2018</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/949e9fb7-b079-491d-9700-3af4e8545c97.html">
    <section class="h text-small text-lighter">Domaine de la Touraize</section>
    <section class="h text-bolder">Crémant du Jura Millésimé - 2018</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/9b57e144-d3e1-45b1-974b-a16a415962cf.html">
    <section class="h text-small text-lighter">Bruno Paillard</section>
    <section class="h text-bolder">Première Cuvée - NV</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/bcaa149d-9a5e-4dbd-b010-7370a0c858d7.html">
    <section class="h text-small text-lighter">Matassa</section>
    <section class="h text-bolder">Brutal Rouge - 2019</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/cf54ea2f-5a9b-4e9a-8a64-1eb490729b6e.html">
    <section class="h text-small text-lighter">Francoise Bedel</section>
    <section class="h text-bolder">Origin'elle - NV</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/ed95a91a-0437-40f1-8e9f-e01086ea0ec6.html">
    <section class="h text-small text-lighter">Krasna Hora</section>
    <section class="h text-bolder">Blanc de Noir Sekt - 2018</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/fd039a96-5a17-4b9a-8ee8-1337c3e99fba.html">
    <section class="h text-small text-lighter">Francoise Bedel</section>
    <section class="h text-bolder">Entre Ciel & Terre (2013) - NV</section>
  </a>

</div>
#+end_export
