- Type :: Red Still, Dry
- Producer :: Weinert
- Vintage :: 2009
- Location :: Argentina, Mendoza
- Grapes :: Cabernet Sauvignon, Malbec, Merlot
- Alcohol :: 14.5
- Sugar :: 2.37
- Price :: 929 UAH, 865 UAH
- Cellar :: 1.0 / 1.0 available

** Producer

It is said that Mr. Raúl de la Mota had a dream of making high quality wine from Malbec grapes in Mendoza. In 1970 Malbec was only on its way to becoming a star in these lands, yet Mr. Raúl de la Mota meets and shares his dream with a Brazilian transportation businessman, Mr. Bernardo C. Weinert. The story is stingy, so I don't know all the reasons for Mr. Bernardo C. Weinert to agree. But it is known that he fell in love with a 80 years old building in Carrodilla, Luján de Cuyo. So in 1975 they started to reconstruct the building and the winery itself. The first harvest was in 1977 and first release was in 1979.

But what makes this winery interesting for us, plebeians? First of all, it is located in Luján de Cuyo, a high altitude region in Mendoza, located in the foothills of Andeas mountains between 800 m and 1500 m elevation. This terroir enables complex and well structured wines. Secondly, Weinert ages wines in the bottle before releasing them. And it's easy to get bottles that are 10+ years old. Thirdly, the price tag is good. This combination deserves to be enjoyed.

** Ratings

*** 2020-11-24 - ★ 8.5

4.2 Alright, this was unexpected. Complex and (if I may) elegant. I would not
guess New World wine here. Lots of blackberry, medicinal herbs, earth, smoke and
meat. Powerful but rounding tannins. I didn't guess it's age, I thought that
it's much younger, but this wine is already 11 years old. Has lots of potential.
Great value.

