- Type :: White Still, Dry
- Producer :: [[barberry:/producers/3d5928c7-97f8-4a20-bad4-14a91e1ec7c9][Éric Chevalier]]
- Vintage :: 2018
- Location :: France, Vin de Table (France)
- Grapes :: Sauvignon Gris
- Alcohol :: 12
- Sugar :: NA
- Price :: 1000 UAH, 1112 UAH
- Cellar :: 1 bottle



This cuvée comes from a maceration of Sauvignon Gris (otherwise called Fié Gris), in whole bunches for 3 to 4 weeks. Aging on lees for 11 to 12 months.

** Producer

Sometimes people who sell wine decide to try on a new role of a vine grower or even a winemaker. Éric Chevalier was a négociant with ten years of experience when he moved to his hometown of Saint-Philbert de Grandlieu, just southwest of Nantes. Next year, in 2006, he ended up taking over the family Domaine. His father, a vigneron, had stopped working the vineyards, and Éric was faced with a difficult choice. Despite being anything but enthusiastic, he decided against replanting or selling vineyards. And instead, he decided not only to continue farming the Domaine but also to produce and bottle all of the family's result of hard work.

In 2020 Éric Chevalier acquired organic certification, a rare achievement in Loire Valley. Especially considering the difficult climate and love for high yields. In addition, Éric Chevalier is one of the few people still planting and producing wines from Fié Gris.

** Ratings

There are no ratings of this wine yet. It's waiting for the right moment, which could be today, tomorrow or even in a year. Or maybe, I am drinking it at this moment... So stay tuned!

