- Type :: White Still, Dry
- Location :: Italy, Vino (IT)
- Grapes :: Field Blend
- Alcohol :: 13.5
- Sugar :: 1
- Price :: 1890 UAH
- Cellar :: 0.0 / 1.0 available

#+begin_quote
Джорджио Мерканделли выращивает более 100-летние лозы в Ольтрепо Павезе, Ломбардия. Джорджио производит вина в стиле «natural wine». «Lanthano Bianco» представляет собой вино, с необычным профилем. Около 10 гектаров виноградников находятся в состоянии крайней естественности, растения полностью предоставлены сами себе. Никакой серы и, прежде всего, меди. В неблагоприятные годы вина не производятся. Все работы проходят исключительно вручную. Эволюция вин Джорджио проходит очень медленно и следует циклам в 5-7 лет. В аромате прослеживаются оттенки восточных специй, меда, каркаде и пряностей. Вкус тонкий, динамичный и сбалансированный, с яркой кислотностью. Разлито без фильтрации.

Спонтанное брожение с использованием диких дрожжей в смоляных чанах, с длительной мацерацией на кожице. Разлито без фильтрации и добавления сульфитов.

Goodwine
#+end_quote

** Ratings

*** 2022-01-11 - ★ 8.5

Deep amber colour and of course it's cloudy. Powerful bouquet with secondary and tertiary notes: caramel, buckwheat honey, sweet spices, hibiscus and acetone. Full-bodied, fresh with medium-high and round tannin. Long aftertaste with flavours of buckwheat honey, quince, candied fruits and caramel. Complex, powerful and delicious skin contact wine.
