- Type :: Red Still, Dry
- Location :: Greece, Naoussa POP
- Grapes :: Xinomavro
- Alcohol :: 13
- Sugar :: 3.1
- Price :: 375 UAH, 365 UAH
- Cellar :: 0.0 / 2.0 available

#+begin_quote
Вино пурпурного цвета со сложным, типичным для сорта ксиномавро ароматом красных
ягод, вишен, ежевики и слив. Вкус полный с округлыми танинами и сбалансированной
кислотностью. Послевкусие продолжительное, насыщенное.

Урожай собирают вручную и тщательно сортируют по прибытию на винодельню.
Спиртовое брожение проходит в нейтральных емкостях под воздействием диких
дрожжей. По завершению малолактической ферментации вино выдерживают в емкостях,
вино бутылируют нефильтрованным.

Goodwine
#+end_quote

** Ratings

*** 2020-11-26 - ★ 6.5

3.5 Fruit-forward Xinomavro from Naoussa. Red berries, leather and subtle raw
meat hints. Medium-light, good tannins. Simple, but easy going, which is nice.

*** 2022-01-25 - ★ 7.5

It became so much better in one year. Pale ruby colour. Aromatic bouquet full of plum, cherry, fallen leaves and red berries compote. Juicy and delicious, fresh with medium body, round medium tannin and good balance. Easy going Xinomavro by wonderful winery.

