- Type :: Red Still, Dry
- Location :: Georgia, Kakhetia
- Grapes :: Jgia
- Alcohol :: 13
- Sugar :: 2.79
- Price :: 690 UAH
- Cellar :: 0.0 / 2.0 available

** Producer

Small producer from Kakhetia. Cultivates Rkatsiteli, Mtsvane and almost extinct Jgia. All wines are hand made. Uses qvevri, of course. Annual production is less than 5000 bottles.

** Ratings

*** 2021-11-04 - ★ 8.5

Amazing wine made of Jgia grapes. Complex bouquet: juniper, grapes,
dye, prune, cherry, cardamon, cinnamon, leather, medicinal herbs and
tea. Interesting evolution in glass. The palate is powerful but
delicate at the same time with nice mineral touch. Interesting and
sophisticated wow-effect wine.

*** 2021-12-13 - ★ 8.5

Happy that I could secure more than one bottle of this beautiful wine
made of 100% Jgia - a rare Georgian grape. Sophisticated and evolving
bouquet of cherry, dark forest berries, pine, juniper, spices, tea and
leather hints. Juicy, mineral and tasty on the palate. Still has its
raw power but shows delicacy at the same time. Unique gem with
wonderful QPR.

