- Type :: Red Still, Dry
- Producer :: [[barberry:/producers/edd81899-a92d-49ad-9566-a6f0c333c220][Patrice Beguet]]
- Vintage :: 2020
- Location :: France, Vin de Table (France)
- Grapes :: Poulsard, Trousseau
- Alcohol :: 11
- Sugar :: 2
- Price :: 892 UAH
- Cellar :: N/A

** Ratings

*** 2021-08-10 - ☆ 7.00

Young and still crazy. Cloudy visually and reductive in 'bouquet': toilet, cranberry, fermented raspberry and VA. Easy and very light, but acidity is out of balance, and you get aftertaste full of VA with some fermented red fruits. It has potential (hence such a high rating), but needs a year or more to settle down and improve.

Tasted together with [[barberry:/producers/edd81899-a92d-49ad-9566-a6f0c333c220][Patrice Beguet]] in 101 Bar.

** Related

#+begin_export html
<div class="flex-container">
  <a class="flex-item flex-item-left" href="/wines/1f7e5557-18aa-4054-a674-9b5f5edfdf19.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Go Together Red - 2019</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/369d38ae-163d-4c8d-bc21-1900c8b72a7d.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Go Together Red - 2018</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/41c61abd-bb8c-4a9c-be77-c2fe756581f3.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Fresh Impression White - 2018</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/67648a12-7d2c-481b-ba2f-707213642f7c.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Oh Yeah - 2020</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/72af4b22-a56f-4f04-a0e7-c6e3a6179600.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Big Bunch Theory Fresh Impression Red - 2020</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/805e6758-4d6a-4c21-9ab4-4045e6ea446c.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Fresh Impression White - 2019</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/e59e3ee3-cfb8-4f3d-8df3-8001d244a624.html">
    <section class="h text-small text-lighter">Patrice Beguet</section>
    <section class="h text-bolder">Three views of a secret - 2020</section>
  </a>

</div>
#+end_export
