- Type :: White Still, Semy sweet
- Producer :: Marco de Bartoli
- Vintage :: 2016
- Location :: Italy, Marsala DOC
- Grapes :: Grillo
- Alcohol :: 18
- Sugar :: 88
- Price :: 915 UAH
- Cellar :: N/A

** Ratings

*** 2020-10-12 - ☆ 7.5

They say Marco de Bartoli has moved the reputation of Marsala. I am not the person to judge here as this is my first Marsala ever. So far I've been enjoying Madeira and wanted to try something new. And I am happy that I did. Fresh lemon notes, mixed with roasted nuts, and dried date fruit. Refreshing, pleasant acidity, citrus flavours with hints of nuts. There is evolution in the taste, good smooth finish, though I think it could be better balanced.

*** 2020-11-05 - ☆ 7.5

Marco de Bartoli has conquered my hearth with his dry whites. Now little by little I surrender to his Marsala. I guess the next step would be something from Pantelleria (love this place thanks to Ben Rye). But right now I have pretty young and simple Marsala. But don't be fooled, it's delicious. It is not as deep as I would love it to be, but expect lemon curd, nuts, dried date fruit. Refreshing and tasty. Definitely want to explore more.

