:PROPERTIES:
:ID:                     2ee42abc-0cb4-458d-b201-3fd1c959d8e9
:END:
- Type :: Rose Sparkling, Brut nature
- Producer :: [[barberry:/producers/040a275b-2e16-4d7a-a557-036bf44d85df][Villa Calicantus]]
- Vintage :: 2018
- Location :: Italy, Vino (IT)
- Grapes :: Corvina, Molinara, Rondinella, Sangiovese
- Alcohol :: 12
- Sugar :: NA
- Price :: 698 UAH, 776 UAH
- Cellar :: N/A



Sollazzo (Enjoy the sun) is a rosé sparkling made of Corvina, Rondinella, Molinara, and Sangiovese. Unfortunately, the grapes are too young - 5 years old.

** Producer
:PROPERTIES:
:ID:                     78f09413-62d6-4f9d-bce8-44b6c5b2d73a
:END:

Some people have to spend a lot of time until they find a path to their favourite craft. Daniele Delaini, a descendant of one of the largest growers of Bardolino in the past, changed several jobs until he 'returned' to his abandoned family estate. After a stink in banking and an attempt to sell Italian wines in Paris, he went to Villa Calicantus, which he inherited from his aunt. The name of the estate comes after her favourite flowering plant.

Daniele started with one hectare of vines around the villa. But the inherited estate was abandoned for many years, and its cellar required complete renovation. And so, in 2011, Daniele was forced to make his first vintage in a nearby garage.

Let's be honest, Bardolino's reputation is quite questionable. For many years many farmers and winemakers were focused on quantity over quality. This resulted in flabby, soulless, and low-quality wines destined to be consumed by unfortunate tourists. Of course, I am exaggerating, but this descent sculped the face of this region.

Villa Calicantus was not operational during the times of industrial and chemical boom that happened in this region. So the nearly forty-year gap in his family's involvement in Bardolino played a crucial role in Daniele's philosophy.

#+begin_quote
Our goal is to bring Bardolino back on the map of great Italian wines, through a rediscovery of the true identity of wine with enormous potential.

[[https://www.villacalicantus.it/en/wine-tasting-in-bardolino-lake-garda/][villacalicantus.it]]
#+end_quote

Today Villa Calicantus owns 8 hectares of vineyards on some of the highest sites in the appellation. As they say, exceptional wine is made in vineyards, so Daniele farmed organically since day one. In 2014 he started the conversion to biodynamics. Each wine comes from only one specific area. Each wine tells a story of a specific vintage, a specific vineyard from a specific sub-area of Bardolino.

In the cellar, nothing is added except for little doses of sulfur. Wine is fermented with indigenous grape yeasts, decanted and bottled following the lunar cycles, not filtered, and not clarified.

** Ratings
:PROPERTIES:
:ID:                     b8f55e76-8eb0-4296-8164-06d86796b423
:END:

*** 2022-07-05 - ☆ 7.20
:PROPERTIES:
:ID:                     ff2f57d5-6f46-4fd5-899b-d53dc8b39de0
:END:

An interesting rosé 'frizzante' bursting with strawberries, pickles, sauerkraut, yeast and red citrus fruits. Nothing overly complex. Medium acidity. Aftertaste is long and flavourful - grapefruit, Sicilian orange and red berries. Lacks volume.

Tasted as part of [[barberry:/posts/2022-07-05-mixed-bag][Mixed Bag Vol. 1]].

** Related
:PROPERTIES:
:ID:                     a9d6f090-3354-4f28-b97c-3cb60ece92a9
:END:

#+begin_export html
<div class="flex-container">
  <a class="flex-item flex-item-left" href="/wines/76c88c36-a8b2-4aac-baf1-7a97765f99cd.html">
    <section class="h text-small text-lighter">Villa Calicantus</section>
    <section class="h text-bolder">Soracuna - 2018</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/38b023df-8c26-45e1-80f7-6be3f53681cc.html">
    <section class="h text-small text-lighter">Éric Chevalier</section>
    <section class="h text-bolder">Cirrus - 2018</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/44ee0d12-de03-42f2-83f0-502be8bd54b0.html">
    <section class="h text-small text-lighter">Matassa</section>
    <section class="h text-bolder">Cuvée Alexandria - 2019</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/4c7ebcd8-9f6a-4158-aff7-ac66179a984f.html">
    <section class="h text-small text-lighter">Domaine du Pélican</section>
    <section class="h text-bolder">Savagnin Ouillé - 2016</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/b34b4714-7bf8-4a52-b0e5-1774e035a4ae.html">
    <section class="h text-small text-lighter">Patrick Sullivan</section>
    <section class="h text-bolder">Rain Field Blend - 2019</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/baf18c42-2e67-4108-967a-d540bc105779.html">
    <section class="h text-small text-lighter">Cascina Bertolotto</section>
    <section class="h text-bolder">Spumante Brut Metodo Classico - NV</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/ddee2b3f-3dcc-4ae6-9c11-31dea06d5d79.html">
    <section class="h text-small text-lighter">Pheasant's Tears</section>
    <section class="h text-bolder">Poliphonia - 2019</section>
  </a>

</div>
#+end_export
