- Type :: Rose Sparkling, Brut nature
- Producer :: [[barberry:/producers/040a275b-2e16-4d7a-a557-036bf44d85df][Villa Calicantus]]
- Vintage :: 2018
- Location :: Italy, Vino (IT)
- Grapes :: Corvina, Molinara, Rondinella, Sangiovese
- Alcohol :: 12
- Sugar :: NA
- Price :: 698 UAH, 776 UAH
- Cellar :: 1 bottle



Sollazzo (Enjoy the sun) is a rosé sparkling made of Corvina, Rondinella, Molinara, and Sangiovese. Unfortunately, the grapes are too young - 5 years old.

** Producer

Some people have to spend a lot of time until they find a path to their favourite craft. Daniele Delaini, a descendant of one of the largest growers of Bardolino in the past, changed several jobs until he 'returned' to his abandoned family estate. After a stink in banking and an attempt to sell Italian wines in Paris, he returned to Villa Calicantus, which he inherited from his aunt. The name of the estate comes after her favourite flowering plant.

Daniele started with one hectare of vines around the villa. But the inherited estate was abandoned for many years, and its cellar required complete renovation. And so, in 2011, Daniele was forced to make his first vintage in a nearby garage.

Let's be honest, Bardolino's reputation is quite questionable. For many years many farmers and winemakers were focused on quantity over quality. This resulted in flabby, soulless, and low-quality wines destined to be consumed by unfortunate tourists. Of course, I am exaggerating, but this descent sculped the face of this region.

Villa Calicantus was not operational during the times of industrial and chemical boom that happened in this region. So the nearly forty-year gap in his family's involvement in Bardolino played a crucial role in Daniele's philosophy.

#+begin_quote
Our goal is to bring Bardolino back on the map of great Italian wines, through a rediscovery of the true identity of wine with enormous potential.

[[https://www.villacalicantus.it/en/wine-tasting-in-bardolino-lake-garda/][villacalicantus.it]]
#+end_quote

Today Villa Calicantus owns 8 hectares of vineyards on some of the highest sites in the appellation. As they say, exceptional wine is made in vineyards, so Daniele farmed organically since day one. In 2014 he started the conversion to biodynamics. Each wine comes from only one specific area. Each wine tells a story of a specific vintage, a specific vineyard from a specific sub-area of Bardolino.

In the cellar, nothing is added except for little doses of sulfur. Wine is fermented with indigenous grape yeasts, decanted and bottled following the lunar cycles, not filtered, and not clarified.

** Ratings

There are no ratings of this wine yet. It's waiting for the right moment, which could be today, tomorrow or even in a year. Or maybe, I am drinking it at this moment... So stay tuned!

