- Type :: Rose Sparkling, Brut
- Producer :: Francois Montand
- Vintage :: NV
- Location :: France, Vin de Table (France)
- Grapes :: Grenache, Cinsault
- Alcohol :: 11.5
- Sugar :: 10
- Price :: 232 UAH, 245 UAH
- Cellar :: 0.0 / 25.0 available

** Producer

Descendant of wine makers, Francois Montand was raised in Champagne. But during WWII he moved to Jura, where he settled and started to produce sparkling wines in traditional method, but with no classification.

** Ratings

*** 2021-09-02 - ★ 7.4

Rose Sparkling wine tasting event at Goodwine TSUM.

Delicate bouquet of cream soda, red apple and apricot flowers. Good
mousse, medium+ acidity. It is simple, it lacks complexity, but well
made and delicious. Cosmic value, at last something except for
mediocre Cava for this price. Everyday drink!

*** 2021-12-10 - ★ 7.25

Simple and straight-forward bubbles that for the last 3 months I
consumed in amounts that I don't want to share with anyone (let's just
say that it's more than 4 cases). Nose full of red berries, peaches,
red apples and white flowers. Nothing extraordinary, just a good
traditional brut for the right price.

*** 2022-05-29 - ★ 7.0

Simple, fruit-forward yet pleasant traditional sparkling for absurdly good price. Little by little finishing those cases of this wine I bought before the war. Red berries, peaches and red apples. Lacks delicacy, but there is something good in this energetic and rough profile with long aftertaste.

