- Type :: Rose Sparkling, Brut
- Location :: France, Vin de Table (France)
- Grapes :: Grenache, Cinsault
- Alcohol :: 11.5
- Sugar :: 10
- Price :: 232 UAH, 245 UAH
- Cellar :: 0.0 / 25.0 available

#+begin_quote
Франсуа Монтан, потомок длинной линии виноделов, вырос на винограднике своей семьи в Шампани. Он был одним из самых влиятельных винных торговцев в регионе. В начале 1940-х годов, во время Второй мировой войны, Франсуа Монтан переехал из Шампани в департамент Юра. С собой Франсуа взял всего несколько виноградных лоз, чтобы посадить их в Юре. Сменив место жительства, Франсуа Монтан сохранил взгляды и убеждения стиля своего виноделия. В Юре он начал новую жизнь и прославился невероятными игристыми винами под маркой "Франсуа Монтан". Благодаря опыту, полученному в Шампани, Монтан производил игристые вина с многогранным ароматом в соответствии с традиционным методом двойного брожения. Сегодня напитки под брендом "Франсуа Монтан" по-прежнему производятся со строгим соблюдением этого традиционного метода, с тщательным выбором лучшего винограда.

[[https://goodwine.com.ua/brut-rose-27770.html][goodwine.com.ua]]
#+end_quote

** Ratings

*** 2021-09-02 - ★ 7.4

Rose Sparkling wine tasting event at Goodwine TSUM.

Delicate bouquet of cream soda, red apple and apricot flowers. Good
mousse, medium+ acidity. It is simple, it lacks complexity, but well
made and delicious. Cosmic value, at last something except for
mediocre Cava for this price. Everyday drink!

*** 2021-12-10 - ★ 7.25

Simple and straight-forward bubbles that for the last 3 months I
consumed in amounts that I don't want to share with anyone (let's just
say that it's more than 4 cases). Nose full of red berries, peaches,
red apples and white flowers. Nothing extraordinary, just a good
traditional brut for the right price.

*** 2022-05-29 - ★ 7.0

Simple, fruit-forward yet pleasant traditional sparkling for absurdly good price. Little by little finishing those cases of this wine I bought before the war. Red berries, peaches and red apples. Lacks delicacy, but there is something good in this energetic and rough profile with long aftertaste.

