- Type :: White Sparkling, Brut
- Location :: France, Champagne AOC
- Grapes :: Chardonnay
- Alcohol :: 12.5
- Sugar :: 2.3
- Price :: 1377 UAH
- Cellar :: 0.0 / 2.0 available

#+begin_quote
Небольшой Шампанский Дом Lamiable находится в Тур-сюр-Марн и
сфокусирован на производстве вин с доминирующей долей пино нуара.
Сделанный полностью из шардоне, выращенного в их родном городе
Тур-сюр-Марн, где преобладают пино нуары, - хотя и не названном «Блан
де Блан» - Brut Cuvee Pheerie демонстрирует плотный, яркий, отнюдь не
тонкий характер. Шампанское сияет оттенками яблок и ядрами персика,
цедрой лимона и грейпфрута, добавляя к шоу ярко выраженной пикантности
с достаточной первичной сочностью для освежения.

[[https://goodwine.com.ua/cuvee-pheerie-q8149.html][goodwine.com.ua]]
#+end_quote

** Ratings

*** 2021-12-24 - ★ 8.25

Took this bottle because some people were praising this producer as an
underappreciated gem. And I definitely didn't expect it to be that
good. 84 months on lees for $50! Not delicate, but charming bouquet:
Jerez, almond galette, crème brûlée, baked apple, lemon and chalk.
Good volume, long persistent aftertaste with nice mineral finish. Yup,
that's definitely good and a great value for sure.

*** 2022-05-17 - ★ 8.5

Amazing value. Considering that it spent 84 months on lees, the price under $50 is a feat in itself. But forget the price, the wine is great. Powerful and straightforward bouquet full of baked apple, jerez, almond galette, crème brûlée and baked apple. Good volume, good development, long persistent aftertaste. Not the first time I enjoy this bottle, and definitely not the last.

