- Type :: White Still, Dry
- Location :: Slovenia, Namizno Vino
- Grapes :: Ribolla Gialla
- Alcohol :: 12.5
- Sugar :: 3.9
- Price :: 1050 UAH
- Cellar :: 0.0 / 2.0 available

Acacia barrels!

#+begin_quote
Янко - прирожденный винодел, делающий натуральное вино. Его
королевство, Kmetija Stekar, находится на полпути между Юлийскими
Альпами и Адриатическим морем, в маленьком городке под названием
Койско, регионе, с прекрасными условиями для выращивания винограда в
западной части Словении. Виноградники расположены на крутых склонах,
на высоте 180 метров над уровнем моря и обрабатываются согласно
органическим принципам. Янко нравится изучать богатые традиции
местного виноделия, основанные на длительной мацерации и спонтанном
брожении с использованием диких дрожжей. «Rebula Prilo» - оранжевое
вино, которое вызывает неподдельные эмоции. Длительная выдержка в
бочках из акации, янтарный цвет, сложный букет из сухофруктов, полевых
цветов, карамели, грецких орехов. Во вкусе отличная кислотность и
соленость, с присутствием танина и хорошей мягкостью на послевкусии.

Goodwine
#+end_quote

#+begin_quote
4.0 Powerful, flavorful, opulent orange wine. Dark amber color, rich
typical nose, full body, tannic, multilayered, long finish.

Zorick Umansky
#+end_quote

** Ratings

*** 2021-05-25 - ★ 8.0

Skin Party #6. Knocking out orange, powerful and aromatic, has many
similarities with Ageno 2015 (with one major distinction, Rebula Prilo
is still freely available). Dried apricots, buckwheat honey, nuts,
caramel, dried flowers. Rich and opulent, tannic, full bodied and
multilayered. The only thing that bothered me is huge amount of VA (so
had to decrease my rating a little bit).

*** 2022-01-11 - ★ 8.0

Great skin contact wine from Goriška Brda. Clean medium amber colour, powerful bouquet showing some age: oranges, dried medicinal herbs, apples and honey. Body dry, full-bodied, tart with powerful and drying tannin. Good balance, long aftertaste, flavours of acetone, honey, quince and medicinal herbs.

