- Type :: Red Still, Dry
- Producer :: [[barberry:/producers/547556c5-86ba-4b9e-a7f9-7776e6963cfc][Marto]]
- Vintage :: 2018
- Location :: Germany, Rheinischer Landwein
- Grapes :: Pinot Blanc, Pinot Grigio, Pinot Noir
- Alcohol :: 10.5
- Sugar :: 0
- Price :: 750 UAH
- Cellar :: N/A

** Ratings

*** 2020-08-10 - ☆ 7.00

Strawberry, cranberry and pine! With subtle barn hints. Bright acidity, good tannins. Overall sophisticated light wine. In the hot evening pairs perfectly well with 'The Foam of Days' by Boris Vian.

*** 2020-08-16 - ☆ 7.00

Not sure why I've got the second bottle, but I not sad at all! Strawberry, pine, soaked apples and pickles, cranberry and thyme. Good mix of different characteristics. Viscous wine with bright acidity and tannins. Long aftertaste (why most of the wines I drink have long aftertaste?) with pine-strawberry flavours.

*** 2020-11-24 - ☆ 7.50

Tasting again in 5 months and I like it more now. It become deeper and more interesting. Now it has less soaked things in aroma, it's mostly about strawberries, leather and paint. Light and pleasant, easy to drink.

** Related

#+begin_export html
<div class="flex-container">
  <a class="flex-item flex-item-left" href="/wines/042cfcdf-fc2e-4716-881b-5546c6124052.html">
    <section class="h text-small text-lighter">Marto</section>
    <section class="h text-bolder">Weiss - 2019</section>
  </a>

  <a class="flex-item flex-item-right" href="/wines/72b542d8-fab8-4147-8436-297f41c46ade.html">
    <section class="h text-small text-lighter">Marto</section>
    <section class="h text-bolder">Weiss - 2018</section>
  </a>

  <a class="flex-item flex-item-left" href="/wines/cfd31303-7b5e-40cd-875b-1d4a293ab0a8.html">
    <section class="h text-small text-lighter">Marto</section>
    <section class="h text-bolder">Crazy Crazy - 2020</section>
  </a>

</div>
#+end_export
