- Type :: Rose Still, Dry
- Location :: Italy, Etna DOC
- Grapes :: Nerello Mascalese
- Alcohol :: 12.5
- Sugar :: 0.2
- Price :: 645 UAH
- Cellar :: 0.0 / 3.0 available

#+begin_quote
Джузеппе Руссо, почитаемый винодел, с большим прошлым пианиста. Органика на виноградниках, выращивание местных сортов, особый терруар Этны, традиционное открытое брожение, позволяет производить элегантные, сбалансированные вина. Etna Rosato 2019 года раскрывается свежими оттенками клюквы, кислой вишни и минералов. Вкус деликатный, обладает приятной свежестью с фруктовым характером. Рекомендуется пить в период 2020-2024 года.

Сегодня вина Этны вызывают все больший интерес на международном рынке, а виноделие Сицилии динамично развивается. Однако всего лишь несколько виноделов производят выдающиеся вина на склонах активного вулкана. Один из них Джузеппе Руссо, который обрабатывает свои виноградники самостоятельно и сам делает вино. Виноград с каждого участка он винифицирует отдельно, чтобы отразить индивидуальность каждого терруара. Многие из старых лоз растущих кустом достигают столетнего возраста, существуя в гармонии с черной, богатой минералами вулканической почвой Этны. В распоряжении хозяйства Girolamo Russo 26 гектаров лоз, но около половины урожая Джузеппе продает, оставляя на собственные нужды лишь виноград со старых лоз. Джузеппе выпускает одно белое, одно розовое и четыре красных вина. Три из которых производятся из различных крохотных крю, а четверное является базовым вином из более молоды лоз. Белое вино Nerina изготавливается из сорта карриканте с добавлением других автохтонных сортов Сицилии.

Виноград собирают немного раньше нежели для красного вина, целые гроздья прессуют и оставляют в контакте с мезгой для обретения цвета. Ферментация и выдержка проходит в стальных емкостях.

[[https://goodwine.com.ua/etna-rosato-51386.html][goodwine.com.ua]]
#+end_quote

** Ratings

*** 2021-07-13 - ★ 7.25

Girolamo Russo is a producer that I am trying to discover for myself
and every wine I taste lacks something to tick for me. Maybe they need
to spend more time in bottle, don't know. Rosato is closed and
elusive. White flowers, grapefruit, peach and cream. The palate is
also creamy with flavours of peach and grapefruit. Overall it's nice,
but restrained, so I could not fully enjoy this wine.

*** 2021-08-19 - ★ 8.0

The last time I tasted this wine, I was disappointed. But then I
tasted Nerina and it returned my faith in Russo. So now giving one
more chance to Rosato. And it's wonderful! Delicate and sophisticated
bouquet full of cheese with mold, grass, sea, spices, red currant.
Medium+ acidity, well balanced, long aftertaste with flavours of
gooseberry, red currant and nice iodine touch.

*** 2022-06-01 - ★ 8.5

Almost a year has passed since my last tasting of this wine. And it's as great as I remember it. Vivid, delicate and sophisticated. It bursts with notes of cheese, sea, spices, red currant, and cranberry. Almost perfectly balanced, vibrant, with amazing taste evolution behaving like a sea wave. Flavours of red currant, sour cheery, Sicilian orange and iodine. One of my favourite light rosé wines, despite bad first experience.

