- Type :: White Sparkling, Extra brut
- Producer :: Francoise Bedel
- Vintage :: NV
- Location :: France, Champagne AOC
- Grapes :: Pinot Meunier, Pinot Noir
- Alcohol :: 12.5
- Sugar :: 4.8
- Price :: 2336 UAH, 2042 UAH
- Cellar :: 0.0 / 2.0 available

** Ratings

*** 2020-08-30 - ★ 8.5

Complex, deep and refreshing Champagne. Sunflower oil, flowers, baked apples, lemon tart and plastic. Very good mousse, perfect refreshing body with very long finish, flavours of baked apples and sunflower seeds. This was very tasty! I really wonder how it plays after some aging.

*** 2021-01-25 - ★ 8.5

Intense, profound and expressive. Ripe apple, brioche, vanilla eclair, oil, barberry candy, flowers. Perfectly balanced, flavourful and oily with bakery hints. Long aftertaste. My second try and second success.

*** 2021-08-17 - ★ 8.5

Wonderful Bedel-style. Oxidative, but more delicate that Origin'elle. Baked apples, flowers, oil, lemon tart, Jerez. Delicious, balanced and sophisticated. Despite complexity remains friendly and approachable.

Tasted after Divych Vechir event.

