#+begin_quote
We sometimes forget how important color and temperature are in assessing wines.

James Laube
#+end_quote

A (professional) sensory analysis of wine breaks it down using eyes, nose, and mouth. We often focus more on the smell and the taste of a particular wine, not talking much about its visuals. Yet, the sight reveals a lot of information about wine: its grape varietal, the region it comes from, some of the winemaking aspects, and its age. Our brain perceives this information even if we don't acknowledge it, or even if we don't know its meaning. Aside from removing the last source of subjective judgement, what else would happen if we won't be able to see the wine? And if both red and white wines are served at room temperature in opaque glasses, would we be able to guess at least the colour? I've heard, from various sources, that it's not as easy as it seems. So let's try!

Honestly, I feared that I would not be able to gather enough people for this format. On one hand, it's more nerdy and wine-focused than our usual events. On the other hand, glasses are pricey and are hard to find. Yet, we have enough people to taste 4 wines. Unfortunately, every person has only one glass, so we taste them sequentially, but in 'pairs'. Meaning, we taste the first two wines, vote, reveal, and then repeat with the second pair.

The plan is to start with a pretty classical pair. A delicate Pinot Noir and oaked Chardonnay, both from Burgundy. And then to try with a more tricky pair - light Cariñena from South Africa and white Châteauneuf du Pape.

1. [[barberry:/wines/345c98e3-665a-416f-83a7-b31d12e29361][Domaine Rossignol-Trapet Savigny-Les-Beaune Les Bas Liards 2019]]
2. [[barberry:/wines/0209f5d1-a27d-45a1-8497-c3aeafe79c6e][Bret Brothers Pouilly-Loché Climat La Colonge 2018]]
3. [[barberry:/wines/d7faed1b-ff73-4f26-be36-633d6664ecfd][Testalonga Baby Bandito Follow Your Dreams 2021]]
4. [[barberry:/wines/670fad73-f37f-4fc2-bb51-44452dc9fbe5][Le Vieux Télégraphe Châteauneuf du Pape Clos La Roquète 2020]]

* Resources
:PROPERTIES:
:ID:                     2e6b3fa3-b4c1-4c4c-b507-f18c84e859d2
:END:

- [[https://www.winespectator.com/articles/test-your-tasting-talent-with-black-wine-glasses-16068][Test Your Tasting Talent With Black Wine Glasses | Wine Spectator]]
- [[https://www.westlakevillageinn.com/the-blind-tasting/][Black Glass Wine Tasting | Westlake Village Inn]]

