Wines:

1. [[barberry:/wines/48f6d914-0ac3-4d79-a5bc-4c384f163db0][Vilmart & Cie Emotion 2012]]
2. [[barberry:/wines/9e587f67-5955-46b7-98d2-6c4c82715685][Ulysse Collin Les Pierrières Blanc de Blancs Extra Brut (2017) NV]]
3. [[barberry:/wines/3f06a9b5-cc2a-4e14-b96b-50cb37f7df46][Jacquesson Aÿ Vauzelle Terme Récolte 2013]]
4. [[barberry:/wines/ac08ddd3-87c9-4e9e-bcb7-2d59da63cec0][Jacques Selosse Exquise Sec NV]]
5. [[barberry:/wines/53cf2258-cbbe-44dc-99a0-5bc6eaf61d04][De Sousa Cuvée des Caudalies 2010]]
6. [[barberry:/wines/d0ea2337-7d61-451b-bf4b-978d2bf34ee1][Bruno Paillard N.P.U. 2008]]

* Bruno Paillard N.P.U. 2008
:PROPERTIES:
:ID:                     60520b50-fc00-4b7e-af13-f155dcac027d
:END:

- sur lie: 120 months
- disgorged: April 2019
- dosage: 3 g/L
- terroir: Montagne de Reims

The grapes selected to create this cuvée come exclusively from 7 of the most sought-after Grands Crus of the Champagne terroir: Oger, Le Mesnil-sur-Oger, Chouilly, Cramant, Verzenay, Mailly-Champagne, and Bouzy. Fermentation was conducted in small old oak barrels in which the wines spent their first 10 months.

An equal split between Pinot Noir and Chardonnay. Both are vinified and matured in small, old oak barrels. Ten years of autolysis in the cellar followed by two years of post-disgorgement rest.

Bottle #14187 / 18798.

#+begin_quote
94+

Disgorged in April 2019 with three grams per liter dosage, Paillard's 2008 Extra-Brut N.P.U. Nec Plus Ultra unwinds in the glass with notes of pear and citrus mingled with hazelnut, toasted bread, dried fruits and warm biscuits. Medium to full-bodied, taut and chiseled, it's concentrated and complex, its tightly wound mid-palate complemented by a pearly mousse and underpinned by chalky grip. While it's introverted today, this is a classic in the making that will show brilliantly with more age on cork, even if it will always remain a comparatively lean, acid-driven marathon runner of a Champagne.

--- [[https://www.robertparker.com/wines/MmdfFuJnZvBqMqCaP/extra-brut-npu-nec-plus-ultra-2008][William Kelley]] on Jan 31, 2022
#+end_quote

https://champagnebrunopaillard.com/en/champagnes/nec-plus-ultra-en/

* De Sousa Cuvee des Caudalies Millésimée 2010
:PROPERTIES:
:ID:                     9d831520-deee-46fa-8a47-de981ef20a92
:END:

- sur lie: 81 months
- disgorged: [2018-04-11 Wed]
- bottled: [2011-07-07 Thu]
- dosage: 4
- terroir: Côte de Blancs

100% Chardonnay 2010. 100% oak barrels.

#+begin_quote
94

The 2010 Cuvée des Caudalies Grand Cru Extra Brut shows a very clear, complex, expressive and highly mineral (or chalky) nose that dominates the ripe and concentrated yet very delicate fruit (100% old vines Chardonnay from the Côte des Blancs) and gives this cuvée its unique expression. Intense, round and fruity on the palate, this is a highly finessed and elegant yet persistent and mineral Caudalies that reveals great purity, finesse and freshness on the finish. This is not powerful at all but is delicate, fresh, refined and charming, leaving the palate with a stimulatingly salty purity and tensioned minerality. This is a great, highly charming and seductive Blanc de Blancs that was bottled in July 2011 and disgorged in January 2017 with a dosage of four grams per liter. Tasted in Reims, April 2018.

--- [[https://www.robertparker.com/wines/hT7B8yJLcyCCfnZWx/cuve-des-caudalies-millsime-grand-cru-extra-brut-2010][Stephan Reinhardt]] on Aug 31, 2018
#+end_quote

#+begin_quote
Refined and aromatic carried on the ripe yellow fruit like plum, pineapple, eat up notes of
honey and ginger.

--- De Sousa
#+end_quote

https://www.champagnedesousa.com/wp-content/uploads/2018/01/Fiche-technique-Caudalie-2010-FR-ENG-1-1.pdf

* Jacquesson Aÿ Vauzelle Terme Récolte 2013
:PROPERTIES:
:ID:                     e26e3788-ba11-4e42-a340-6fc47d12a266
:END:

- sur lie: ~96 months
- disgorged: May 2022
- dosage: 0
- terroir: Vallée de la Marne, Aÿ

Mid, south-facing slope; alluvial soil rich in limestone on blocks of Campanian chalk; 2,500 vines of Pinot Noir planted on 30 ares in 1980; permanent Cordon de Royat pruning.

2520 bottles and 196 magnums produced.

#+begin_quote
95 (for 2009)

Disgorged without dosage in May 2019, the 2009 Extra-Brut Grand Cru Aÿ - Vauzelle Terme is showing nicely, offering up inviting aromas of pear, honeycomb, dried white flowers and hints of dried fruit and nuts. Medium to full-bodied, elegantly fleshy and vinous, it's broad and textural, with ripe but racy acids, a delicate mousse and a long, sapid finish.

--- [[https://www.robertparker.com/wines/22u7B4AMoYjHXJRTK][William Kelley]], Sep 17, 2020
#+end_quote

* Vilmart & Cie Emotion 2012
:PROPERTIES:
:ID:                     8be82ce0-babe-4cbf-89ae-7b89e6106cfa
:END:

- sur lie: 60 months
- disgorged: May 2018
- dosage: 8
- terroir: Rilly-la-Montagne
- ageing: ten months in oak barrels of 228 litres
- mlf: none

Blending composed of 60 % Pinot Noir (“Rosé de Saignée”) and 40 % Chardonnay classified Premier Cru and from vines of sixty years old age in Rilly-la-Montagne.

#+begin_quote
94

Disgorged in January 2018, Vilmart's new 2012 Brut Emotion is showing beautifully, wafting from the glass with aromas of orange oil, red berries, yellow plums and toasted almonds. Medium to full-bodied, deep and concentrated, it's racy and incisive, with chalky structuring extract and a pillowy mousse, concluding with a penetrating finish. It's a blend of 60% Pinot Noir and 40% Chardonnay from 45-year-old vines, vinified in barrels for 10 months without malolactic fermentation.

--- [[https://www.robertparker.com/wines/uHDQenxnJmzQqMGgn/brut-emotion-2012][William Kelley]] on Sep 17, 2020
#+end_quote

https://www.champagnevilmart.fr/en/vins/emotion-2014-en/

* Jacques Selosse Exquise NV
:PROPERTIES:
:ID:                     06136550-169e-4139-814e-1c138d8fcac2
:END:

- sur lie:
- disgorged: [2020-01-30 Thu]
- dosage: 24
- terroir: Avize and Cramant

100% Chardonnay.

#+begin_quote
94

The NV Exquise Sec is a Blanc de Blancs sourced in Avize and Cramant and assembles the vintages 2009, 2010 and 2011. Bottled in July 2012 and disgorged in October 2017 with a dosage of 24 grams per liter, this is a lovely, aromatic Champagne with cherry notes on the nose. Round and juicy on the densely woven palate, with sweet cherry flavors, this is a very aromatic, elegant, very well structured and complex Sec with an immersive finish. Tasted at the domaine in April 2018.

Jacques Selosse, Anselme's father, created Domaine Jacques Selosse in 1949 in Avize along with his wife. The domain still bears his name, though Anselme took over the estate in 1974. Domaine Jacques Selosse produces 57,000 bottles of Champagne every year from grapes grown and harvested on 7.5 hectares of vines spread over Chardonnay plots in the Côte des Blancs—Avize, Cramant, Oger and Le Mesnil-sur-Oger—and a few Montagne de Reims plots, dedicated to growing Pinot Noir, in Aÿ, Ambonnay and Mareuil-sur-Aÿ.

--- [[https://www.robertparker.com/wines/uvXTytDGeX7qcoMz9/exquise-sec-nv][Stephan Reinhardt]] on Aug 31, 2018
#+end_quote

* Ulysse Collin Les Pierrières Blanc de Blancs Extra Brut (2017) NV
:PROPERTIES:
:ID:                     c7af602b-7d49-4de2-9df4-944f062dbd79
:END:

- sur lie: 36 months
- disgorged: March 2021
- dosage:
- terroir:

#+begin_quote
97

There are 5,400 bottles of the NV Extra-Brut Blanc de Blancs Les Pierrières (2017), disgorged in February 2022 after 48 months on the lees—and this is the last time there will be two disgorgements, as from next year onward, Les Pierrières will systematically see 48 months' tirage before disgorgement. Wafting from the glass with scents of confit citrus fruit, lemon zest, spring flowers, almond paste, pastry cream and wet stones, it's medium to full-bodied, satiny and precise, with terrific cut and tension, concluding with a long, saline finish. An additional year before disgorgement delivers a less primary, more integrated, seamless Champagne.

Olivier Collin continues to produce some of the most brilliant and compelling wines in contemporary Champagne, and this new set of releases is no exception. I've written extensively about Collin in the past, so rather than reprising that material here, I refer readers to my feature in the End of August 2019 Issue 244 of The Wine Advocate. Evolutions and refinements worthy of note, however, continue: the 2018 vintage was the first in which Collin was equipped with a new state-of-the-art press from Coquard, permitting even greater precision; and as of this year, he's advanced the date of tirage a touch, with a view to being able to work in a less hurried fashion, without the pressure of an imminent harvest.

In Issue 244 End of August 2019 of The Wine Advocate, I published an in-depth feature on the wines of Olivier Collin, wines that readers will by now have realized that I consider to be among the very best being produced in contemporary Champagne. Collin is putting in the hard work at every stage of the process, and that's driven by an unquenchable will to improve that's rare even among the wine world's elite. The latest evolution is a new disgorging line, which means that Collin can reduce the amount of sulfites he adds at disgorgment all the while delivering a fresher, more vibrant result: and it's typical of his attention to detail that he's reduced the dose less for Les Maillons than for the other cuvées, given Pinot Noir's more oxidative tendencies. Meanwhile, the percentage of foudre-aged reserve wines continues to increase (foresight validated both by the resulting qualitative improvements and, more pragmatically, by the frosts of spring 2021), as does the time wines spend sur lattes between tirage and disgorgment, several limited release late-disgorged bottlings showing the direction in which Collin wishes his entire production ultimately to evolve. And the novelty? That's the Jardin d'Ulysse, a new cuvée, described in detail in the accompanying tasting notes, that represents Collin's first cuvée to blend cépages. As ever, I left Congy invigorated after a several hours' encounter with wines that are as profound as they are ambitious.

--- [[https://www.robertparker.com/wines/2CxG8cSPfirYKybxZ/extra-brut-blanc-de-blancs-les-pierrires-2017-nv][William Kelley]] on Aug 31, 2022
#+end_quote
