Hannes Storm is a winemaker from South Africa dedicated to expressing terroirs of WO Hemel-en-Aarde Valley. After 12 vintages of working with Pinot Noir and Chardonnay he discovered two tiny parcels of land with exceptional terroirs and planted them with Pinot Noir in 2008. His first vintage saw the light in 2012 and after 18 months in bottle, the wines were released in August 2014.

His approach - handcraft, small production, careful viticulture, minimal intervention in the cellar.

Now he works with 3 plots:

- Vrede Pinot Noir and Chardonnay - low-vigor, stony, clay-rich Bokkeveld (Buck Veld) shale soil in the Hemel-en-Aarde Valley.
- Ignis Pinot Noir - decomposed granite soil in the Upper Hemel-en-Aarde Valley.
- Ridge Pinot Noir, also from low-vigour, stony, clay-rich Bokkeveld shale soil in the Hemel-en-Aarde Ridge.

Since WO Hemel-en-Aarde Valley is divided into Valley, Upper Valley and Ridge, this means that Hennes grows Pinot Noir in all 3 appellations of Hemel-en-Aarde Valley. And in fact, as of [2021-09-14 Tue] he is the only winemaker with this sort of achievement.

2019 was a culmination of of three years of bone-dry soils. Although vines are drought-tolerant, 2019 was the year when the stress reached a crescendo. Vines only purpose is to nurture its offspring - grapes and seeds. And when the vines are stressed, they are focusing so much energy in so few grapes. As result, 2019 is very small in production, but very concentrated and powerful in terms of potential. Vrede was produced only 275 cases, Ignis - 290 cases, Ridge - 340 (all about Pinot Noir).

Interestingly, before Hennes Storm started his own project, he worked as a winemaker in Hamilton Russell Vineyards.

** Wines

#+attr_html: :class wines-table
|                                                          name | vintage |     grapes |                   region | rating |
|---------------------------------------------------------------+---------+------------+--------------------------+--------|
| [[barberry:/wines/5ca2fbaf-43a6-4973-9533-20f55ee2594f][Vrede Pinot Noir]] |    2017 | Pinot Noir | WO Hemel-en-Aarde Valley |   8.75 |
| [[barberry:/wines/967d2311-5188-4cdb-ac6a-6ec94c6e40e0][Ridge Pinot Noir]] |    2017 | Pinot Noir | WO Hemel-en-Aarde Valley |   8.00 |
| [[barberry:/wines/b837734a-480c-455b-98e6-25a04b7095ff][Vrede Pinot Noir]] |    2019 | Pinot Noir | WO Hemel-en-Aarde Valley |   8.50 |
