Craig & Carla Hawkins, without any doubt, are revolutionizing the South African wine industry. After long years of traveling around the world and making wines in known and established wineries (like [[barberry:/producers/cdc80e0e-1163-4b33-916d-e6806e5073e3][Matassa]] and Niepoort Vinhos S.A.), they decided to settle down in Swartland and start their own winery. The year was 2008, and they produced 2 barrels of macerated Chenin Blanc. It is considered the first macerated wine in the whole of South Africa. They had to fight for the right to export their wines as regulators were against letting these wines out to the market. All those sediments and other traces of low intervention winemaking were quite suspicious back then. But there is nothing to spoil, as Craig and Carla are famous in the wine world.

In the 2015 they bough Bandits Kloof farm in the northern mountains of Swartland. Climate is similar to Sicilian, so they planted Frappato, Macabeo, Carignan, Mataro, Grenache and Garnacha Blanca.

As they say, 'made from grapes'. And nothing more (except for a tiny bit of sulphites).

** Wines

#+attr_html: :class wines-table
|                                                                         name | vintage |       grapes |       region | rating |
|------------------------------------------------------------------------------+---------+--------------+--------------+--------|
|         [[barberry:/wines/2adba2d9-cc62-4e2b-bcec-5bc363fc2194][Baby Bandito Stay Brave]] |    2017 | Chenin Blanc | WO Swartland |   6.50 |
|         [[barberry:/wines/8ad2d430-ba67-47e0-a257-c05ffe537bff][Baby Bandito Stay Brave]] |    2019 | Chenin Blanc | WO Swartland |   6.88 |
| [[barberry:/wines/a00de9a6-3e60-4ab4-8b81-279995809572][El Bandito I Wish I was a Ninja]] |    2021 |    Colombard | WO Swartland |   7.20 |
|            [[barberry:/wines/c77d5fcf-70d9-4e11-afa1-ee89e3efc2d4][Baby Bandito Chin Up]] |    2020 |     Cinsault | WO Swartland |   7.50 |
|       [[barberry:/wines/cd920007-4ce3-4985-8aef-24c39ad97437][El Bandito I am the Ninja]] |    2020 | Chenin Blanc | WO Swartland |   7.50 |
|                 [[barberry:/wines/d38aadd5-6c84-40a0-93c9-8ff6b7468553][El Bandito Skin]] |    2019 | Chenin Blanc | WO Swartland |   7.50 |
