:PROPERTIES:
:ID:                     1d138765-cf10-4a32-a3c6-b1d2a053dab3
:END:
Sometimes people who sell wine decide to try on a new role of a vine grower or even a winemaker. Éric Chevalier was a négociant with ten years of experience when he moved to his hometown of Saint-Philbert de Grandlieu, just southwest of Nantes. Next year, in 2006, he ended up taking over the family Domaine. His father, a vigneron, had stopped working the vineyards, and Éric was faced with a difficult choice. Despite being anything but enthusiastic, he was against replanting or selling vineyards. And instead, he decided not only to continue farming the Domaine but also to produce and bottle all of the family's result of hard work.

In 2020 Éric Chevalier acquired organic certification, a rare achievement in Loire Valley. Especially considering the difficult climate and region's love for high yields. In addition, Éric Chevalier is one of the few people still planting and producing wines from Fié Gris.

** Wines
:PROPERTIES:
:ID:                     0bfa3c16-38cb-4358-b957-385eef71b96d
:END:

#+attr_html: :class wines-table
|                                                name | vintage |         grapes |                region | rate |
|-----------------------------------------------------+---------+----------------+-----------------------+------|
| [[barberry:/wines/38b023df-8c26-45e1-80f7-6be3f53681cc][Cirrus]] |    2018 | Sauvignon Gris | Vin de Table (France) | 8.00 |
