:PROPERTIES:
:ID:                     0e008ff7-caa1-4bc0-98fe-824f244ab2d1
:END:
Bodegas Peixes is the new project of the 2 guys of [[barberry:/producers/0608acc9-e36c-4cff-970e-0f2489d3011a][Fedellos do Couto]], Jesús Olivares and Curro Bareño, outside D.O. Ribeira Sacra, right in the Ourense massif, with vineyards that are exposed to the cold right to the limit where the grapes can have a good ripening. These are some of the highest vineyards in Galicia at 600-850 metres above sea level.

The 60-80 year-old gobelet trained vines grow along sinuous stone terraces. They are field blends of Mencía, Mouraton, Grao Negro, Garnacha Tintorera, Bastardo and Sousón which include 10-15% of white varietals Godello, Dona Blanca, Colgadeira and Palomino. Farming is a mix of organic and sustainable. Jesús and Curro work six hectares themselves, by hand, and with growers who manage a further two hectares. The winemaking is low intervention and constant across their three cuveés: they use whole clusters, long macerations and cool fermentations with indigenous yeasts. Wines are matured in large neutral oak and bottled without fining or filtration.

** Wines
:PROPERTIES:
:ID:                     58371b8c-5859-45e2-b896-6aa5c7c22adc
:END:

No wines of this producer are present on this site. How did you find this page?
