It is said that Mr. Raúl de la Mota had a dream of making high quality wine from Malbec grapes in Mendoza. In 1970 Malbec was only on its way to becoming a star in these lands, yet Mr. Raúl de la Mota meets and shares his dream with a Brazilian transportation businessman, Mr. Bernardo C. Weinert. The story is stingy, so I don't know all the reasons for Mr. Bernardo C. Weinert to agree. But it is known that he fell in love with a 80 years old building in Carrodilla, Luján de Cuyo. So in 1975 they started to reconstruct the building and the winery itself. The first harvest was in 1977 and first release was in 1979.

But what makes this winery interesting for us, plebeians? First of all, it is located in Luján de Cuyo, a high altitude region in Mendoza, located in the foothills of Andeas mountains between 800 m and 1500 m elevation. This terroir enables complex and well structured wines. Secondly, Weinert ages wines in the bottle before releasing them. And it's easy to get bottles that are 10+ years old. Thirdly, the price tag is good. This combination deserves to be enjoyed.

** Wines

#+attr_html: :class wines-table
|                                                                         name | vintage |                             grapes |      region | rate |
|------------------------------------------------------------------------------+---------+------------------------------------+-------------+------|
|              [[barberry:/wines/5c2c2225-14c9-45cb-94b8-a40f8ad3b5f7][Cabernet Sauvignon]] |    2010 |                 Cabernet Sauvignon |     Mendoza | 7.75 |
|            [[barberry:/wines/60de313a-fc2e-46dd-92d2-4793e97ef93b][Carrascal Chardonnay]] |    2021 |                         Chardonnay |     Mendoza | 7.50 |
| [[barberry:/wines/24a83b0b-3c1b-4412-8b5d-febaf2394108][Cavas de Weinert Cask Selection]] |    2009 | Cabernet Sauvignon, Malbec, Merlot |     Mendoza | 8.50 |
|                          [[barberry:/wines/1cef4a62-828f-47ca-8489-ea911196b860][Merlot]] |    2011 |                             Merlot |     Mendoza |    - |
|                      [[barberry:/wines/64cb0bbe-8a1f-4909-8a99-c4ecfcec14af][Montfleury]] |    2020 |                         Pinot Noir | Gualtallary | 7.40 |
