Ulysse Collin is a legendary Champagne producer based in Congy. Owned by the family that actively growth vines since 1812 in Coteaux du Petit Morin (located in Marne but south of the Grand Crus in the Côte des Blancs). These days Olivier stands behind the name.

In 1987 Oliver's father stopped independent production of wines and started renting family's vines to big Champagne houses. As young student, Oliver took a trip to Burgundy, where he was amazed by wines from Côte de Beaune, especially by singularity of the various climats. So he decided to reclaim vieyards back from big négociant.

In 2003 recovered 4.5 hectares and started working on restoring the soils and vines. The year was tough, so he didn't produce any wine that year and simply sold everything. But in 2004 he started his production from Chardonnay which resulted in 5400 bottles released in the future.

In 2005 Olivier got back an additional 4.2 hectares of vines. And the second Champagne was made in 2006, this time a Blanc de Noirs.

Plots:

- Les Pierrières, 1.2 hectares, 40 years old vines. Shallow, poor topsoil 10 to cm deep over the rocky subsoil of soft chalk with carbonated silex or Onyx.
- Les Maillons, 2 hectares, near the town of Sézanne in the coteaux du Sézannais. Clays rich in iron.
- Les Enfers.

So far produces 6 distinct wines (each one from a singe vineyard):

- Blanc de Blancs Les Pierrières (first vintage is 2004)
- Blanc de Blancs Les Roises (first vintage is 2008)
- Blanc de Blancs Les Enfers (first vintage is 2010)
- Blanc de Noirs Les Maillons (first vintage is 2006)
- Rose Les Maillons (first vintage is 2011)
- Jardin d’Ulysse (first vintage is 015)

** Wines

#+attr_html: :class wines-table
|                                                                                                  name | vintage |     grapes |        region |  rate |
|-------------------------------------------------------------------------------------------------------+---------+------------+---------------+-------|
|            [[barberry:/wines/fa32e9d0-b448-4094-9c58-3a371d9dfe33][Les Enfers Blanc des Blancs Extra Brut (2014)]] |      NV | Chardonnay | Champagne AOC | 10.00 |
|            [[barberry:/wines/870ccf3b-4295-4932-b8f7-10998dddd6ec][Les Maillons Blanc de Noirs Extra Brut (2016)]] |      NV | Pinot Noir | Champagne AOC |  9.00 |
|            [[barberry:/wines/f78e11df-ba1e-49d8-a567-d26bccbb2b33][Les Maillons Blanc de Noirs Extra Brut (2017)]] |      NV | Pinot Noir | Champagne AOC |  9.00 |
|        [[barberry:/wines/9e6ddc62-a7f8-4b3e-9c50-f8ef00bcda06][Les Pierrières Blanc des Blancs Extra Brut (2017)]] |      NV | Chardonnay | Champagne AOC | 10.00 |
| [[barberry:/wines/09fbe9bf-7fdf-43a9-869a-5186d39bcf30][Les Pierrières Blanc des Blancs Extra Brut Magnum (2007)]] |      NV | Chardonnay | Champagne AOC |  8.00 |
|             [[barberry:/wines/50353325-007d-429d-b70b-f9d40206fe8d][Les Roises Blanc de Blancs Extra Brut (2015)]] |      NV | Chardonnay | Champagne AOC |  9.00 |
