Arianna Occhipinti is a winemaker from Vittoria who founded her own winery in 2004, bottled her first commercial vintage in 2006 and today works exclusively with estate fruit. Her 25 hectares feature only autochthonous varieties - 50% Frappato, 35% Nero d'Avola and 15% white varieties Albanello and Zibibbo. Almost all vines are young as she planted them, most of them a guyot-trained. But she also added to her holdings 60-years-old albarello-trained vines which she initially rented.

Total production is about 10,000 cases annually.

Her uncle is Giusto Occhipinti, proprietor of Vittoria's most famous winery, [[barberry:/producers/512e0678-4812-4cee-b090-911416bcc0e2][COS]]. Arianna started at age 16 in his cellars and loved it, enough to go to oenology school and to jump right into her own production. Giusto inspired her for working in a non-bulk-driven style, using organic viticulture, picking by hand, using native-yeast fermentations. She started with 1 hectar of abandoned vines attached to a family vacation house.

#+begin_quote
Not irrigating, harvesting late and not using fertilizers are the secret to making more elegant wines in the area. The freshness and minerality in my wines come from the subsoils. Any wine made from young vines or chemically grown vines feeding only off of the top soil will have the cooked, hot characteristics people associate with wine from warm regions.
#+end_quote

She started using Biodynamic Farming principles. There is zero irrigating in her vineyards in this hot, windy climate! Cover crops including fava beans and other useful plants grow between every other row. New plantings are massale selections only. Juice and wine are moved only by gravity. There is no new oak.

SP68 wines are vinified and aged in small concrete tanks, with no oak of any kind and no punchdowns. The red is a version of Cerasuolo di Vittoria DOCG, but with shorter aging for a fresher take on this regional signature.

Siccagno is a 100% Nero d'Avola, which is aged in old oak only. The same goes for her higher-tier Frappato only wines.

Arianna is regarded as a symbol of success in the world of Biodynamic Farming and Natural Wine Making. She has remained committed to those principles while evolving from her originally more dogmatic outlook. Below is her response to importer Jules Dressner's question about her feeling on the term "natural wine":

#+begin_quote
I make natural wine, but this is a term I'm beginning to be less and less comfortable with, because its implications are very complicated. I really want to stress that my main goal is to make a good wine that reflects where it comes from, and for me the only way to successfully do this is to make the wine naturally. When I first started, people were just starting to talk about natural wine. It was very important to me to think about all these issues, and in those early years I definitely had a more militant attitude about it. Making natural wine was a mission, something worth fighting for. Now that I've grown up a little bit, the mission is making wine of terroir. You have to respect the vineyards, and nature in general. When I wake up in the morning, I want to feel free. Making this wine is my opportunity to feel free. So again, my goal is not to make natural wine, working this way is a process to make good wine.
#+end_quote

** Wines

#+attr_html: :class wines-table
|                                                             name | vintage |                 grapes |                     region | rate |
|------------------------------------------------------------------+---------+------------------------+----------------------------+------|
|       [[barberry:/wines/429ad446-96ad-4005-8306-85656d7e2f6d][Bombolieri BB]] |    2016 |               Frappato |        IGP Terre Siciliane | 9.00 |
|       [[barberry:/wines/004fb7af-4256-490e-b511-b860c0dc5f78][Bombolieri BB]] |    2017 |               Frappato |        IGP Terre Siciliane | 9.00 |
|    [[barberry:/wines/116b633c-dc12-45bf-a6b4-2e7c4a9dfd9e][Fossa di Lupo FL]] |    2017 |               Frappato |        IGP Terre Siciliane | 8.50 |
|         [[barberry:/wines/3f9bfb82-e694-43d5-80b1-11d91ac107e9][Grotte Alte]] |    2014 | Frappato, Nero d'Avola | Cerasuolo di Vittoria DOCG | 9.00 |
|         [[barberry:/wines/9368685a-9c95-4099-a7a3-0662a2a8ce99][Il Frappato]] |    2018 |               Frappato |        IGP Terre Siciliane | 8.50 |
|         [[barberry:/wines/d84a421b-e4f0-4c9b-a2d3-0735f7d1f378][Pettineo PT]] |    2017 |               Frappato |        IGP Terre Siciliane | 8.75 |
|         [[barberry:/wines/06266426-66eb-463f-a4bc-3fd38f6e2543][SP68 Bianco]] |    2015 |     Zibibbo, Albanello |        IGP Terre Siciliane | 8.25 |
|         [[barberry:/wines/68abcb0e-bc4b-4b31-90cf-be3d56071e23][SP68 Bianco]] |    2019 |     Zibibbo, Albanella |        IGP Terre Siciliane | 8.25 |
|         [[barberry:/wines/fe7baaab-b6e1-43c7-b475-2fbacc3e84d4][SP68 Bianco]] |    2020 |     Zibibbo, Albanello |        IGP Terre Siciliane | 7.50 |
|          [[barberry:/wines/b6956647-cca8-45cd-a4f3-890f5360d94f][SP68 Rosso]] |    2014 | Frappato, Nero d'Avola |        IGP Terre Siciliane | 7.80 |
|          [[barberry:/wines/9fa2fcd7-07c0-40ac-b824-37a885885ad6][SP68 Rosso]] |    2019 | Frappato, Nero d'Avola |        IGP Terre Siciliane | 7.69 |
|            [[barberry:/wines/da9ba7c7-b796-48bc-88e5-3904846a03a8][Siccagno]] |    2015 |           Nero d'Avola |        IGP Terre Siciliane | 8.00 |
|            [[barberry:/wines/958808fe-25a7-402e-84f6-4fd05aa9d23a][Siccagno]] |    2017 |           Nero d'Avola |                Sicilia DOC | 8.50 |
| [[barberry:/wines/e9577901-8db7-4178-bc60-462ccdee35c3][Vino di Contrada SM]] |    2020 |                 Grillo |                Sicilia DOC | 7.75 |
