:PROPERTIES:
:ID:                     ea9e1393-fd5d-4c4e-874b-60df07b0b9e9
:END:
Wonderful winemaker from Champagne.

According to her interview with Goodwine, she believes that wine making requires intervention from people. There is critical difference between Low Intervention and no intervention at all.

#+begin_quote
На мой взгляд, совсем не вмешиваться в процесс производства опасно. Человек необходим, чтобы вино не стало уксусом. Я никогда не добавлю сульфитов больше, чем нужно, или не стану добавлять их вовсе, если винтаж мне это позволит. Вино должно быть понятным в плане чистоты вкуса, внешнего вида и ароматов. Я говорю сейчас о Шампани. Не знаю, как в других регионах, а у нас погодные условия таковы, что здесь не получится не прикасаться к вину, если вы хотите сделать что-то хорошее. К тому же, я глубоко убеждена, что лозы находяться в энергетической взаимосвязи с тем, кто за ними смотрит, поэтому нет ничего страшного в том, что человек вмешивается в процесс производства. Даже наоборот.

Один мой импортер из северных страх однажды сказал мне, что предпочитает продавать только натуральные вина. Вечером мы пошли в ресторан, сделали заказ и выбрали натуральное вино. Нам принесли напиток коричневого цвета, с очень странным и неприятным запахом. Если натурально вино такое, я не хочу быть натуралистом. Во время сбора урожая я ставлю бокал с виноградным соком на бочку и смотрю каждый час, как меняется цвет. Если сок остается светлым, мы добавим меньше сульфитов, если начнет темнеть - добавим больше. Я не отношусь к виноделам-экстремистам, которые ничего не делают.

Guilde to Goodwine #38
#+end_quote

** Wines
:PROPERTIES:
:ID:                     e99b730b-ded6-49e8-aa2c-f9e18929edb3
:END:

#+attr_html: :class wines-table
|                                                                     name | vintage |                                grapes |        region | rate |
|--------------------------------------------------------------------------+---------+---------------------------------------+---------------+------|
|   [[barberry:/wines/fd039a96-5a17-4b9a-8ee8-1337c3e99fba][Entre Ciel & Terre (2013)]] |      NV |             Pinot Meunier, Pinot Noir | Champagne AOC | 8.50 |
|   [[barberry:/wines/40a31b63-1452-4566-9557-b9f078ff6d64][Entre Ciel & Terre (2014)]] |      NV | Pinot Meunier, Pinot Noir, Chardonnay | Champagne AOC | 8.50 |
| [[barberry:/wines/ca7dc126-0ea4-4245-93db-f07a87301a7e][L'Âme de la Terre Millésime]] |    2006 | Pinot Meunier, Chardonnay, Pinot Noir | Champagne AOC | 9.00 |
|                 [[barberry:/wines/cf54ea2f-5a9b-4e9a-8a64-1eb490729b6e][Origin'elle]] |      NV | Pinot Meunier, Chardonnay, Pinot Noir | Champagne AOC | 8.38 |
