#+begin_quote
Sous le Végétal is a collaborative wine project between Jason Ligas of Domine Ligas and Patrick Bouju of Domaine la Bohéme. This project finds them on the beautiful island of Samos in Greece, located one mile off the coast of Turkey.

Sous le Végétal actively avoids the industrial farming practices that dominate winemaking in Greece and have opted to do extensive work in the vineyards to restore a healthy permaculture for their vines and the rich assortment of volcanic soils. Their farming practices are biodynamic and organic, down to the utilization of herbs and natural balms to heal and protect the vines.

Each cuvée features Muscat Blanc à Petits Grains. The goal of this project is to show the different expressions of this grape in all of the different microclimates on the island. Every grape is harvested by hand and fermented and aged in a succession of vessels specific to each wine.

In Jason’s words, “This project is entirely geared towards a very specific level of quality, and in order to nourish this project, I rely on the microcosmos, on the infinitely small. Furthermore, I believe in the infinitely slow.”

[[https://zrswines.com/wine-producer/sous-le-vegetal/][zrswines.com]]
#+end_quote

** Wines

#+attr_html: :class wines-table
|                                                          name | vintage |          grapes | region | rate |
|---------------------------------------------------------------+---------+-----------------+--------+------|
|           [[barberry:/wines/55d3286d-d7ce-4659-abca-b0bee73944a9][Octave]] |    2018 | Muscat de Samos |  Oinos | 8.00 |
| [[barberry:/wines/ddff653a-4abb-4715-b2d3-82c7e06171df][Palli et Genesia]] |    2018 | Muscat de Samos |  Oinos |    - |
