Joško Gravner is considered to be father of macerated white wines trend. Before he produced his first amber wine, he was a promising star of modern and technological wine making scene. He confessed that he would purchase any new piece of equipment he could find. His life turned upside down after trip to California back in 1987. California was (and maybe still) a destination for many winemakers as this region represents triumph and possibilities of /new/. No wonders, as Californian wines won Judgement of Paris in 1976 and this event dramatically changed wine world. Joško Gravner was taking the same path as Californian wine makers - oak, science, additives and all that cool stuff. But after tasting 1000 wines in 10 days he was simply astonished by faceless and tasteless results. And he realised that this is the road to a dead end. Now he knew, how not to produce wines.

His searching lasted almost a decade. Basically he was studying history of wine making and was searching for a way to produce authentic wines that talk in language of land and history. Long story short, he found out that (a) his ancestors made skin contact wines here in Collio/Brda and (b) Georgia has a very long history of wine making (more than 8000 years) and they've been making skin contact wines for quite a long period.

In 1997 (after devastating 1996) he produced his first vintage of extensively macerated Ribolla. And after 3 years, when this vintage become ready, Gambero Rosso, Italian wine & food magazine that has huge influence on the industry, gave a devastating assessment of this new style. As result, 80% of 1997 Ribolla were returned to winery. Joško Gravner was crushed, but realised that this is actually the way to go.

In the same 2000, Joško Gravner visited Georgia and ordered 11 qvevri. Unfortunately only 2 of them were properly delivered to his winery. So he started to actually use qvevri for production only in 2001. And nowadays he owns more than 45 of them!

Interestingly, Ribolla and Breg (two wines produced by Joško Gravner) had a word 'Anfora' printed on the labels of 2001 vintage. However they were not 100% fermented in anfora till 2003. Even more, qvevri was not used for Breg Rosso production till 2005. And after some time, in 2007 they decided to remove this word from all labels as this information was redundant - all their wines where fermented in qvevri now.

And today wines produced by Joško Gravner are treated as the highest manifestation of skill. Many people consider his Ribolla the best orange wine in the world.

** Citations
:PROPERTIES:
:ID:                     942c9390-962b-4652-8f75-8ab9d2a8c41b
:END:

#+begin_quote
Йошко Ґравнер вважає за краще залишати гребні для зброджування. Його виноградні ягоди набувають дуже легкого напилення сіркою, коли потрапляють на виноробню (проте навіть це роблять тільки з першими кількома партіями і лише для того, щоб упевнитися, що бродіння розпочнеться якомога плавніше).

Кожна стадія зброджування повністю відбувається у грузинських квеврі, закопаних у погребі. Ягоди самопливом поміщають у квеврі, і бродіння розпочинається природним шляхом. Цю суміш перемішують чітко за графіком кожні три години між п`ятою ранку та одинадцятою вечора. Це виснажливий процес, який може тривати понад годину. Під час зброджування квеврі накривають картоном, щоб уберегти від мух. Після бродіння їх герметично закривають, щоб запобігти проникненню кисню.

"Ріболла Джалла" зберігається зі своїми шкірками та гребнями у квеврі близько півроку. Після цього вино знімають з осаду та переміщують в інше квеврі на наступні п`ять місяців.

Коли минає рік, вино переливають у дуже великі ботті зі славонського дуба (ємністю від 2000 до 5000 літрів), де витримка триває іще шість років. Зрештою вино розливають у пляшки, не фільтруючи і не поліруючи, а ще через кілька місяців випускають у продаж.

Ґравнер вважає за краще застосовувати трошки сірки під час переливання вина, хоча її загальний рівень у готових винах залишається мінімальним.

Amber Revolution
#+end_quote

#+begin_quote
Ґравнерські "Брег" та "Ріболла Джала" мали помаранчевий написа anfora на етикетках вінтажу 2001 року, хоча ці вина не ферментувалися на 100% в амфорах до 2003 року. "Брег Россо" навіть не виготовляли у квеврі до 2005 року. З 2007 року позначка anfora була видалена з усіх етикеток, оскільки родина Ґравнерів вирішила, що в такій інформації більше нама потреби.

Amber Revolution
#+end_quote

** Wines

#+attr_html: :class wines-table
|                                                        name | vintage |         grapes |             region | rate |
|-------------------------------------------------------------+---------+----------------+--------------------+------|
|        [[barberry:/wines/2d320bfb-05fb-4c2c-9ce8-81b52e6eff76][Ribolla]] |    2010 | Ribolla Gialla | IGP Venezia Giulia | 8.50 |
| [[barberry:/wines/8d575670-c594-4f55-b330-6ed0a1e63d3d][Ribolla Anfora]] |    2004 | Ribolla Gialla | IGP Venezia Giulia | 9.00 |
