:PROPERTIES:
:ID:                     40b37f4a-0e5e-4b74-84d2-0182e0a8146f
:END:
Domaine Matassa is a small, naturally farmed estate located in the township of Calce in the Val d'Agly region of Roussillon, Pyrenee-Orientales, France. As of 2022, they own 15 hectares of vineyards around the village of Calce. Vines are between 30 and 115 years old. Their focus is on the indigenous varieties of Northern Catalunya, including Grenache Gris, Maccabeu, Muscat d'Alexandrie (also known as Zibbibo), Lladonner Pelut (the Catalan Grenache), Carignan, and Mourvedre. Their wines are gentler in terms of alcohols, tannins and oak influence, more lively wines in terms of acidity or, ideally, deeper mineral sensations of freshness.

The estate is owned by three incredible people - Tom Lubbe, his wife Nathalie Gauby and Sam Harrop MW. Tom and Sam are from New Zealand, while Nathalie is from Roussillon. And Matassa is located in Roussillon... Sounds suspicious. Cherchez la femme!

Tom Lubbe was born in New Zealand but grew up in South Africa, where he established the famous The Observatory. Together with [[barberry:/producers/c7f2173e-1b32-4e44-8da0-bd36f04b3ae0][Eben Sadie]], Tom ignited the wine revolution in the Swartland region - fresher, purer, with fewer winemaker interventions between grape and bottle.

But before becoming a star of Cape Town, Tom worked for Louise Hofmeyer. She used exclusively indigenous yeasts and worked with lower yields and little or no new wood. In 1999, to gain more experience with Mediterranean grapes, Louise recommended Tom to do a stage at the legendary Domaine Gauby in Calce, in France's Roussillon. Initially, he planned to work there for 3 months only, but Gérard Gauby quickly befriended Tom and invited him to return for three more vintages. This is where he met his wife, Nathalie Gauby, who happens to be Gérard's sister.

The birth of their first child made Tom reconsider moving back to South Africa, opting to stay in to start his own estate. Matassa was founded in 2003. Yet they didn't have a cellar, so their first vintage was made in the recently married couple's living room. Gérard felt so bad about this that he gave Tom the old Gauby in 2004.

Now many people come to Matassa to gain experience from the legendary winemaker.

** Wines
:PROPERTIES:
:ID:                     e35157d0-d4cf-4745-99af-a69918fb85cf
:END:

#+attr_html: :class wines-table
|                                                          name | vintage |                        grapes |                region | rate |
|---------------------------------------------------------------+---------+-------------------------------+-----------------------+------|
|    [[barberry:/wines/beb5669b-5c8c-4c11-ac52-37d225a86bc3][Ace of Spades]] |    2019 |          Monastrell, Cariñena | Vin de Table (France) | 8.00 |
|    [[barberry:/wines/4a2db391-157a-45ac-9fcf-f44ad28d7548][Brutal Orange]] |    2020 |                       Macabeo | Vin de Table (France) | 7.50 |
|     [[barberry:/wines/bcaa149d-9a5e-4dbd-b010-7370a0c858d7][Brutal Rouge]] |    2019 |           Syrah, Muscat Blanc | Vin de Table (France) | 7.25 |
| [[barberry:/wines/44ee0d12-de03-42f2-83f0-502be8bd54b0][Cuvée Alexandria]] |    2019 |                       Zibibbo | Vin de Table (France) | 8.25 |
| [[barberry:/wines/22085dbc-44c2-4b02-bb15-625d0395c818][Cuvée Alexandria]] |    2020 |                       Zibibbo | Vin de Table (France) | 8.00 |
| [[barberry:/wines/4f6d8434-a726-4e9a-955a-745813fdd7d1][Cuvée Marguerite]] |    2020 | Macabeo, Zibibbo, Muskateller | Vin de Table (France) | 8.00 |
|        [[barberry:/wines/bb9c19ad-0571-4346-9bda-088dfaa9a658][El Carner]] |    2020 |             Grenache, Macabeo | Vin de Table (France) | 8.00 |
|        [[barberry:/wines/308e3982-753f-4251-96fd-29379e2e0de0][Mambo Sun]] |    2020 |                      Grenache | Vin de Table (France) | 8.00 |
|       [[barberry:/wines/6c45e619-c75e-43d1-9f11-2896fd46994b][Olla Rouge]] |    2019 |             Grenache, Macabeo | Vin de Table (France) | 8.00 |
|        [[barberry:/wines/370e2f0f-46c0-464f-a27b-49894634e4c2][Rollaball]] |    2020 |          Monastrell, Cariñena | Vin de Table (France) | 7.75 |
