La Stoppa is a legendary historic estate that was founded in 19th century by a lawyer named Giancarlo Ageno. Initially focused on Bordeaux varieties, nowadays its vineyards are occupied by local Barbera, Bonarda and Malvasia. Elena Pantaleoni, current owner of the estate, works closely with famous enologist Giulio Armani (that has his own side project called Denavolo) to craft wines expressive of place and grape. They are advocates of minimal intervention along with usage of huge Slavonian oak botti and used French barriques. Also they are farming organically since 1990's and in 2008 they even acquired proper certification.

** Wines

#+attr_html: :class wines-table
|                                               name | vintage |                                           grapes |     region | rating |
|----------------------------------------------------+---------+--------------------------------------------------+------------+--------|
| [[barberry:/wines/1f4e920e-bfd4-4624-8445-fa8480962c17][Ageno]] |    2015 | Malvasia di Candia Aromatica, Ortrugo, Trebbiano | IGP Emilia |   8.54 |
| [[barberry:/wines/f72778c8-5571-403e-a386-20cffdbf1459][Ageno]] |    2017 | Malvasia di Candia Aromatica, Ortrugo, Trebbiano |  Vino (IT) |   8.00 |
| [[barberry:/wines/d760ef98-0e8f-457e-8e0c-d102169fe4bd][Ageno]] |    2019 | Malvasia di Candia Aromatica, Ortrugo, Trebbiano |  Vino (IT) |   8.50 |
