Patrick Sullivan works with his wife Megan in Yarra Valley to produce authentic wines on their farm in the Strezleki ranges, Baw Baw Shire, Gippsland, Australia. Patrick portrays himself as a farmer and not a winemaker. His vines are pure, intriguing and honest. His labels are catchy. Don't believe me? Just take a closer look!

#+begin_quote
I do not put myself in the category of Natural Wines. I only make wine. Natural Wine is a constructed term that I do not like very much. I make wine in the way I like it and in the style that I like to drink and I do not feel better than someone who acidifies or uses selected yeasts. I do not do it because I do not like it. I do it differently.

Patrick Sullivan
#+end_quote

Patrick's path to winemaking began at a young age. Some say that at age of 12, he spent time planting vines during the school break. His personal site says that his first vinous "whiff" came whilst climbing the hills on a farm his family once owned. In any case, this initial spark developed into fascination and determination. So after finishing high school, Patrick spent two years travelling in Europe to learn winemaking techniques. His love for the craft only grew, so once he returned to his homeland, he studied botany and actuarial science. After post-graduate, Patrick wanted to learn from somebody. And so he went on to gain invaluable experience by working alongside respected winemakers (such as Stuart Proud, William Downie, Anna Martens and Eric Narioo) in various organically and biodynamically managed vineyards in Victoria.

After some time, he gained enough experience, knowledge and confidence to start own projects.

See [[barberry:/producers/8dbcc9b6-8d56-4a50-8f0e-dd96c241abc1][Jumping Juice]].

** Wines

#+attr_html: :class wines-table
|                                                                  name | vintage |                       grapes |    region | rate |
|-----------------------------------------------------------------------+---------+------------------------------+-----------+------|
| [[barberry:/wines/e3066d69-912c-4727-ae59-de6327702828][Baw Baw Shire Chardonnay]] |    2019 |                   Chardonnay | Gippsland | 8.00 |
|                [[barberry:/wines/db5c5f52-ab04-489c-b6b7-232f64badfb4][Bullswamp]] |    2019 |                   Chardonnay | Gippsland | 8.25 |
|         [[barberry:/wines/b34b4714-7bf8-4a52-b0e5-1774e035a4ae][Rain Field Blend]] |    2019 | Cabernet Franc, Pinot Grigio | Gippsland | 8.00 |
