:PROPERTIES:
:ID:                     fbd97f71-769f-4ec2-a963-ceb3e4019d95
:END:
Dominique Lucas is a 5th generation winemaker who migrated from his native Burgundy, frustrated with the region's reliance on chemicals. He is focused on making Chasselas in the Savoie that stands with the best white wines of France. Les Vignes de Paradis is located on the shores of Lake Geneva (Lac Leman).

His vines are separated into 27 parcels of different soil composition. All are harvested by hand. Most of them are Chasselas, but he also has tiny parcels of Savagnin, Pinot Gris, Gamay, Chardonnay and Chenin Blanc. These are not old vines, but in the right hands...

** Wines
:PROPERTIES:
:ID:                     9b5d7658-038b-4f11-9da0-ded0565f662e
:END:

#+attr_html: :class wines-table
|                                                         name | vintage |       grapes |                 region | rate |
|--------------------------------------------------------------+---------+--------------+------------------------+------|
|          [[barberry:/wines/084f2900-816b-4687-bceb-9fe28995f7cc][Chenin]] |    2019 | Chenin Blanc |  Vin de Table (France) | 7.40 |
| [[barberry:/wines/969b7bbf-2917-476f-859b-fcb1fb9f8bb3][Pinot Gris M...]] |    2019 |   Pinot Gris | Vin Des Allobroges IGP |    - |
